2023-04-14 10:21:15 ERROR [GiftCertificateService.save()] GiftCertificate with given name:[big data] already exists.
2023-04-14 10:21:15 ERROR [ExceptionHandler] Handled GiftCertificateAlreadyExistsException exception/error...
2023-04-14 10:21:20 ERROR [GiftCertificateService.save()] rollback !!!
2023-04-14 10:21:20 ERROR [ExceptionHandler] Handled Exception exception/error...
