2023-04-11 19:30:03 ERROR [GiftCertificateService.save()] GiftCertificate with given name:[big data] already exists.
2023-04-11 19:30:03 ERROR [ExceptionHandler] Handled GiftCertificateAlreadyExistsException exception/error...
2023-04-11 19:30:29 ERROR [GiftCertificateService.update()] rollback !!!
2023-04-11 19:30:29 ERROR [ExceptionHandler] Handled Exception exception/error...
2023-04-11 19:31:02 ERROR [GiftCertificateService.update()] rollback !!!
2023-04-11 19:31:02 ERROR [ExceptionHandler] Handled Exception exception/error...
